### ISSUE TITLE
Mainframe Walker Loyalty Ability Icons Appear Above Card

### ISSUE THREAD

**Issue by ryanmueller28** [CajunAvenger/Cajun-Style-Templates#11]
The Mainframe Single Side walkers has an issue where the Loyalty ability counter icons are above the frame of the card like so:

![WalkerLooksLike](https://user-images.githubusercontent.com/55604547/107163186-cc028100-696d-11eb-9b70-c1f8168df012.PNG)

My console output looks like:

![ConsoleOutput1](https://user-images.githubusercontent.com/55604547/107163154-a1b0c380-696d-11eb-8c5c-d8f6b0c32410.PNG)

I'm a back end engineer, so styling isn't my strong suit, but what's the fix?

**Comment by CajunAvenger** [comment]
The Mainframe Planeswalkers update requires [MSE 2.1.x](https://github.com/twanvl/MagicSetEditor2/releases). If you don't want to update for some reason, `Cajun-Style-Templates/magic-m15-mainframe-planeswalker.deprecated-mse-style/` holds the old style.

**Comment by ryanmueller28** [comment]
Thank you for this. Closing this issue.
